
/* This file was generated by idltool 53.6. Do not edit */

#include <stdbool.h>

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCOMPACT_H
#include <libraries/kittyCompact.h>
#endif

extern ULONG                VARARGS68K _kittycompact_Obtain(struct kittyCompactIFace *);
extern ULONG                VARARGS68K _kittycompact_Release(struct kittyCompactIFace *);
extern char *               VARARGS68K _kittycompact_makeLookupTable(struct kittyCompactIFace *);
extern void                 VARARGS68K _kittycompact_FreeLookupTable(struct kittyCompactIFace *, void * table);
extern void *               VARARGS68K _kittycompact_makeContext(struct kittyCompactIFace *);
extern void                 VARARGS68K _kittycompact_FreeContext(struct kittyCompactIFace *, void * table);
extern bool                 VARARGS68K _kittycompact_convertPacPic(struct kittyCompactIFace *, unsigned char * data, struct PacPicContext * context);
extern bool                 VARARGS68K _kittycompact_convertPacPicData(struct kittyCompactIFace *, unsigned char * data, int o, struct PacPicContext * context);
extern void                 VARARGS68K _kittycompact_plotUnpackedContext(struct kittyCompactIFace *, struct PacPicContext * context, struct retroScreen * screen, int x, int y);
