
/* This file was generated by idltool 53.6. Do not edit */

#include "kittyCompact_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _kittycompact_Obtain,
    _kittycompact_Release,
    NULL,
    NULL,
    _kittycompact_makeLookupTable,
    _kittycompact_FreeLookupTable,
    _kittycompact_makeContext,
    _kittycompact_FreeContext,
    _kittycompact_convertPacPic,
    _kittycompact_convertPacPicData,
    _kittycompact_plotUnpackedContext,
    _kittycompact_plotUnpackedContextClip,
    (APTR)-1
};

