/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyCompact
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittyCompact.h>

#include <interfaces/kittyCompact.h>
#include <proto/exec.h>
#include <assert.h>

struct kittyCompactIFace * IkittyCompact = NULL;
static struct Library * __kittyCompactBase;
static struct kittyCompactIFace * __IkittyCompact;

/****************************************************************************/

extern struct Library * kittyCompactBase;

/****************************************************************************/

void kittyCompact_main_constructor(void)
{
    if (kittyCompactBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __kittyCompactBase = kittyCompactBase = (struct Library *)IExec->OpenLibrary("kittycompact.library", 0L);
        assert(kittyCompactBase != NULL);
    }

    __IkittyCompact = IkittyCompact = (struct kittyCompactIFace *)IExec->GetInterface((struct Library *)kittyCompactBase, "main", 1, NULL);
    assert(IkittyCompact != NULL);
}
__attribute__((section(".ctors.zzzy"))) static void
(*kittyCompact_main_constructor_ptr)(void) USED = kittyCompact_main_constructor;

/****************************************************************************/

void kittyCompact_main_destructor(void)
{
    if (__IkittyCompact)
    {
        IExec->DropInterface ((struct Interface *)__IkittyCompact);
    }
    if (__kittyCompactBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyCompactBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*kittyCompact_main_destructor_ptr)(void) USED = kittyCompact_main_destructor;

/****************************************************************************/

