/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyCompact
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittyCompact.h>

#include <interfaces/kittyCompact.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * kittyCompactBase = NULL;
static struct Library * __kittyCompactBase;

/****************************************************************************/

void kittyCompact_base_constructor(void)
{
    if (kittyCompactBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __kittyCompactBase = kittyCompactBase = (struct Library *)IExec->OpenLibrary("kittycompact.library", 0L);
    assert(kittyCompactBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*kittyCompact_base_constructor_ptr)(void) USED = kittyCompact_base_constructor;

/****************************************************************************/

void kittyCompact_base_destructor(void)
{
    if (__kittyCompactBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyCompactBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*kittyCompact_base_destructor_ptr)(void) USED = kittyCompact_base_destructor;

/****************************************************************************/

