#ifndef KITTYCOMPACT_INTERFACE_DEF_H
#define KITTYCOMPACT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.6.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCOMPACT_H
#include <libraries/kittyCompact.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct kittyCompactIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct kittyCompactIFace *Self);
	ULONG APICALL (*Release)(struct kittyCompactIFace *Self);
	void APICALL (*Expunge)(struct kittyCompactIFace *Self);
	struct Interface * APICALL (*Clone)(struct kittyCompactIFace *Self);
	char * APICALL (*makeLookupTable)(struct kittyCompactIFace *Self);
	void APICALL (*FreeLookupTable)(struct kittyCompactIFace *Self, void * table);
	void * APICALL (*makeContext)(struct kittyCompactIFace *Self);
	void APICALL (*FreeContext)(struct kittyCompactIFace *Self, void * table);
	bool APICALL (*convertPacPic)(struct kittyCompactIFace *Self, unsigned char * data, struct PacPicContext * context);
	bool APICALL (*convertPacPicData)(struct kittyCompactIFace *Self, unsigned char * data, int o, struct PacPicContext * context);
	void APICALL (*plotUnpackedContext)(struct kittyCompactIFace *Self, struct PacPicContext * context, struct retroScreen * screen, int x, int y);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* KITTYCOMPACT_INTERFACE_DEF_H */
