#ifndef INLINE4_KITTYCOMPACT_H
#define INLINE4_KITTYCOMPACT_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYCOMPACT_H
#include <libraries/kittyCompact.h>
#endif
#include <interfaces/kittyCompact.h>

/* Inline macros for Interface "main" */
#define makeLookupTable() IkittyCompact->makeLookupTable() 
#define FreeLookupTable(table) IkittyCompact->FreeLookupTable((table)) 
#define test() IkittyCompact->test() 

#endif /* INLINE4_KITTYCOMPACT_H */
